# Generated by Django 3.2 on 2023-06-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, help_text='Укажите Имя', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, help_text='Укажите фамилию', max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, help_text='Укажите отчество', max_length=255, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('last_name', 'first_name', 'patronymic'),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Укажите наименование', max_length=255, verbose_name='Наименование')),
                ('release_year', models.PositiveIntegerField(help_text='Укажите год выпуска', verbose_name='Год выпуска')),
                ('status', models.CharField(choices=[('В наличии', 'Available'), ('На прочтении', 'On Reading'), ('Зарезервирована', 'Reserved')], default='В наличии', help_text='Укажите статус книги', max_length=20, verbose_name='Статус книги')),
                ('authors', models.ManyToManyField(help_text='Авторы', to='core.Author', verbose_name='Выберите авторов')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, help_text='Укажите имя', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, help_text='Укажите фамилию', max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, help_text='Укажите отчество', max_length=255, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
                'ordering': ('last_name', 'first_name', 'patronymic'),
            },
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('В наличии', 'Available'), ('На прочтении', 'On Reading'), ('Зарезервирована', 'Reserved')], help_text='Укажите статус книги', max_length=20, verbose_name='Статус книги')),
                ('start_datetime', models.DateTimeField(help_text='Укажите дату и время начала действия статуса', verbose_name='Дата и время начала действия статуса')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Укажите дату и время окончания действия статуса', null=True, verbose_name='Дата и время окончания действия статуса')),
                ('book', models.ForeignKey(help_text='Укажите книгу', on_delete=django.db.models.deletion.PROTECT, to='core.book', verbose_name='Книга')),
                ('reader', models.ForeignKey(blank=True, help_text='Выберите читателя', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.reader', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'История учета',
                'verbose_name_plural': 'Истории учета',
            },
        ),
    ]
