# Generated by Django 3.2 on 2023-06-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='Авторы', related_name='books', to='core.Author', verbose_name='Выберите авторов'),
        ),
        migrations.AlterField(
            model_name='bookhistory',
            name='book',
            field=models.ForeignKey(help_text='Укажите книгу', on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookhistory',
            name='reader',
            field=models.ForeignKey(blank=True, help_text='Выберите читателя', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.reader', verbose_name='Читатель'),
        ),
    ]
