# Generated by Django 3.2 on 2023-06-13 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230612_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_datetime', models.DateTimeField(help_text='Укажите дату возврата книги', verbose_name='Дата возврата книги')),
                ('is_sent', models.BooleanField(default=False, help_text='Укажите, отправлено ли уведомление', verbose_name='Отправлено уведомление')),
                ('book', models.ForeignKey(help_text='Укажите книгу, подлежащую возврату', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.book', verbose_name='Книга, подлежащая возврату')),
                ('reader', models.ForeignKey(help_text='Укажите читателя, имеющего долг по возврату', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.reader', verbose_name='Читатель, имеющий долг по возврату')),
            ],
        ),
    ]
